import { writeFileSync, readFileSync } from "node:fs";
import {
  editorTokenDefinitions as definitions,
  editorTokenGroups as groups,
  editorTokenNames as names,
  editorTokenVariable as variable,
} from "../packages/editor/src/theme/tokens.ts";

const tiers = [
  [
    "ref",
    "Ref · 原始色板",
    "原始色值，只被 sys 层引用。组件与宿主样式不要直接使用。",
  ],
  [
    "sys",
    "Sys · 语义角色",
    "表面、操作、状态、字体、形状、尺寸、层级。宿主定制主题时覆盖这一层。",
  ],
  [
    "cmp",
    "Cmp · 组件 token",
    "时间线、预览、控件部件。只通过 var() 引用 sys，不含原始值。",
  ],
];
const isDifferent = (name, key) =>
  key in definitions[name] &&
  definitions[name][key] !== definitions[name].light;

/** How each token is exposed to Tailwind. Returns [themeEntries, utilityName] or null (not exposed). */
function tailwind(name) {
  const { kind, tier } = definitions[name];
  if (tier === "ref") return null;
  const v = `var(${variable(name)})`;
  if (kind === "color")
    return {
      theme: [[`--color-${name}`, v]],
      usage: `bg-/text-/border-${name}`,
    };
  if (name === "font-ui")
    return { theme: [["--font-sans", v]], usage: "font-sans" };
  if (name === "font-mono")
    return { theme: [["--font-mono", v]], usage: "font-mono" };
  if (name.startsWith("text-")) {
    const size = name.slice(5);
    const theme = [[`--text-${size}`, v]];
    if (["2xs", "xs", "sm", "base"].includes(size))
      theme.push([`--text-${size}--line-height`, "var(--bve-line-height)"]);
    return { theme, usage: `text-${size}` };
  }
  if (name.startsWith("radius-"))
    return {
      theme: [[`--radius-${name.slice(7)}`, v]],
      usage: `rounded-${name.slice(7)}`,
    };
  if (name.startsWith("shadow-"))
    return {
      theme: [[`--shadow-${name.slice(7)}`, v]],
      usage: `shadow-${name.slice(7)}`,
    };
  if (name.startsWith("z-"))
    return { utility: [name, "z-index", v], usage: name };
  return null;
}

const block = (selector, values) =>
  `${selector} {\n${values.map(([name, value]) => `  ${variable(name)}: ${value};`).join("\n")}\n}\n`;

const tokensCss =
  "/* Generated by scripts/generate-theme.mjs; edit theme/tokens.ts. */\n" +
  block(
    ".bve-scope",
    names.map((name) => [name, definitions[name].light]),
  ) +
  block(
    ".bve-scope.dark",
    names
      .filter((n) => isDifferent(n, "dark"))
      .map((n) => [n, definitions[n].dark]),
  ) +
  block(
    '.bve-scope[data-density="comfortable"]',
    names
      .filter((n) => isDifferent(n, "comfortable"))
      .map((n) => [n, definitions[n].comfortable]),
  );

const themeLines = [];
const utilityLines = [];
for (const name of names) {
  const mapped = tailwind(name);
  if (!mapped) continue;
  for (const [key, val] of mapped.theme ?? [])
    themeLines.push(`  ${key}: ${val};`);
  if (mapped.utility) {
    const [utility, property, val] = mapped.utility;
    utilityLines.push(`@utility ${utility} {\n  ${property}: ${val};\n}\n`);
  }
}
const tailwindCss =
  "/* Generated by scripts/generate-theme.mjs; edit theme/tokens.ts. */\n" +
  "/* Default palette/radius/shadow scales are reset so only theme tokens produce utilities. */\n" +
  "@theme inline {\n  --color-*: initial;\n  --radius-*: initial;\n  --shadow-*: initial;\n" +
  themeLines.join("\n") +
  "\n}\n\n" +
  utilityLines.join("\n");

const cell = (text) => (text === undefined ? "—" : `\`${text}\``);
let doc =
  "# 主题 Token 清单\n\n由 `scripts/generate-theme.mjs` 从 `src/theme/tokens.ts` 生成，不要手改。\n\n" +
  "- appearance 的键为下表变量去掉 `--bve-` 前缀后的名称；颜色均为完整 CSS 颜色值。\n" +
  "- compact 使用默认尺寸，comfortable 仅改变表中注明的控件尺寸，不改变时间线几何。\n" +
  "- “Tailwind”列是该 token 对应的工具类；没有对应工具类的 token 只能通过 `var(--bve-*)` 使用。\n" +
  "- 三层关系：`ref`（原始色板）→ `sys`（语义角色）→ `cmp`（组件 token）。组件代码只允许使用 sys / cmp。\n\n" +
  `共 ${names.length} 个 token。\n\n`;
for (const [tier, title, intro] of tiers) {
  const tierGroups = Object.entries(groups).filter(([, g]) => g.tier === tier);
  const count = names.filter((n) => definitions[n].tier === tier).length;
  doc += `## ${title}（${count}）\n\n${intro}\n\n`;
  for (const [id, group] of tierGroups) {
    doc += `### ${group.title}\n\n${group.hint}\n\n| 变量 | 类型 | 浅色默认 | 深色默认 | comfortable | Tailwind |\n| --- | --- | --- | --- | --- | --- |\n`;
    doc +=
      names
        .filter((n) => definitions[n].group === id)
        .map((n) => {
          const t = definitions[n];
          const usage = tailwind(n)?.usage;
          return `| \`${variable(n)}\` | ${t.kind} | ${cell(t.light)} | ${t.dark !== t.light ? cell(t.dark) : "同浅色"} | ${isDifferent(n, "comfortable") ? cell(t.comfortable) : "—"} | ${usage ? cell(usage) : "—"} |`;
        })
        .join("\n") + "\n\n";
  }
}

for (const [path, content] of [
  ["packages/editor/src/theme/tokens.generated.css", tokensCss],
  ["packages/editor/src/theme/tailwind.generated.css", tailwindCss],
  ["docs/theme-tokens.md", doc.trimEnd() + "\n"],
]) {
  const url = new URL("../" + path, import.meta.url);
  if (process.argv.includes("--check")) {
    if (readFileSync(url, "utf8") !== content)
      throw new Error(`Outdated generated file: ${path}`);
  } else writeFileSync(url, content);
}
